# Generated by Django 6.1.1 on 2026-09-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table=None,
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('data_candidatura', models.DateField()),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('link_vaga', models.URLField(blank=True)),
                ('modalidade', models.CharField(choices=[('Remoto', 'Remoto'), ('Híbrido', 'Híbrido'), ('Presencial', 'Presencial')], max_length=20)),
                ('status', models.CharField(choices=[('Aplicado', 'Aplicado'), ('Triagem', 'Triagem'), ('Entrevista RH', 'Entrevista RH'), ('Entrevista Gestor', 'Entrevista Gestor'), ('Teste Técnico', 'Teste Técnico'), ('Finalista', 'Finalista'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Desistiu', 'Desistiu')], default='Aplicado', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('ultimo_contato', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='cadastro.empresa')),
            ],
        ),
    ]
