# Generated by Django 6.1.1 on 2026-09-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_candidatura_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_normalized', models.CharField(editable=False, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='name_normalized',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
