# Generated by Django 6.1.1 on 2026-09-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_cargo_empresa_name_normalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_normalized', models.CharField(editable=False, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='cadastro.empresa')),
            ],
        ),
    ]
