# Generated by Django 6.1.1 on 2026-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_empresaalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='local_vaga',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
