# Generated by Django 6.1.1 on 2026-09-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_empresa_city_alter_empresa_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='city',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='state',
        ),
    ]
