# Generated by Django 6.1.1 on 2026-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_remove_empresa_city_remove_empresa_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagina_carreiras',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='setor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
