# Generated by Django 6.1.1 on 2026-09-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_solicitacaoempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('request', 'Requisição'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login recusado'), ('empresa_aprovada', 'Empresa aprovada'), ('empresa_rejeitada', 'Empresa rejeitada')], db_index=True, max_length=30)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('rota', models.CharField(blank=True, max_length=500)),
                ('status_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
