# Generated by Django 6.1.1 on 2026-09-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='referer',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
